name: CI

# Triggered on GitHub push event
on: push

# Define single job called build
jobs:
  
  build:
  
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.10", "3.11", "3.12"]
    
    runs-on: ${{matrix.os}}
    
    steps:
    
    # A job is a sequence of steps
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python ${{matrix.python-version}}
      uses: actions/setup-python@v5
      with: 
        python-version: ${{matrix.python-version}}
    
    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt .
        
    - name: Test with PyTest
      run: |
        python3 -m pytest --cov=inflammation.models tests/test_models.py
        
        
        
        
        
        
         
