name: CI

# Triggered on GitHub push event
on: push

# Define single job called build
jobs:
  
  build:
    
    # Specify OS
    runs-on: ubuntu-latest
    
    steps:
    
    # A job is a sequence of steps
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with: 
        python-version: "3.12"
    
    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
        
    - name: Test with PyTest
      run: |
        python3 -m pytest --cov=inflammation.models tests/test_models.py
        
        
        
        
        
        
         
